server:
  port: 8082

logging:
  level:
    com.nta.slack: debug

spring:
  application:
    name:
      nta_slack
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    username: slack
    password: nta_slack
    url: jdbc:postgresql://localhost:5432/slack_db




feign:
  client:
    config:
      default:
        requestInterceptors:
          - com.nta.slack.integracao.config.WebInterceptor
        loggerLevel: full

slack:
  client-id: ops
  client-secret: put-yours
  oauth-token:
    bot-token: some-bot-token
    user-token: some-user-token


