version: '3.1'

services:
  db_nta_slack:
    image: postgres
    environment:
      POSTGRES_USER: slack
      POSTGRES_PASSWORD: nta_slack
      POSTGRES_DB: slack_db
    volumes:
      - ./docker-volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8081

volumes:
  psql: